### ISSUE TITLE
Can't open 'src/webshoot.js'

### ISSUE THREAD

**Issue by jriisj** [joergpatz/docker-phantomjs#1]
When running the command 
`docker run --rm -v /volume1/docker/screenshots/:/tmp joergpatz/phantomjs webshoot.js http://dr.dk webshot01.png`

I get the error 
`Can't open 'src/webshoot.js'`

**Comment by joergpatz** [comment]
HI, `src/webshoot.js` is just an example. people can make different [phantomjs web capture scripts](http://phantomjs.org/examples/). So you should include the `webshoot.js` file in your mountpoint (phantomjs is searching for within the running container). For instance, In your case just copy `webshoot.js` to `/volume1/docker/screenshots/`.

Then run:
`docker run --rm -v /volume1/docker/screenshots/:/tmp joergpatz/phantomjs webshoot.js http://dr.dk webshot01.png`

OR

`cd /volume1/docker/screenshots/` and run the container with:
`docker run --rm -v $(pwd):/tmp joergpatz/phantomjs webshoot.js http://dr.dk webshot01.png`

**Comment by jriisj** [comment]
Ah yes, that makes sense. Thanks for taking the time to reply to a rookie.
